### ISSUE TITLE
"Error while saving the note" - OsX 10.8.4 & Ubuntu 12.04 - Vim, Nano, Sublime Text

### ISSUE THREAD

**Issue by heindl** [VitaliyRodnenko/geeknote#131]
Hello,

After installing the program from Github, and I like what you're doing.

I'm able to login and find any available notes.

However, each time I trying to save a note, either in Vim, Nano, or Sublime Text, I'm met with an "Error while saving the note". This is occurs in OsX and Ubuntu.

Are there any logs that could point to the cause of this?

Thanks for your work.

EDIT (13:08)

It looks like it works at least for newly created notes. So there must be an invalid character issue somewhere in the text. Will try to identify.

EDIT (13:55)

Looks like Sublime Text 3 doesn't work. Geeknote saves the file before it opens in a Sublime Text window.

**Comment by acofer** [comment]
Having same problem with OS X and console vim. .geeknote/error.log:

2015-02-24 11:05:51,867 geeknote wrapper 70 : Error: updateNote : EDAMUserException(errorCode=11, parameter='Element type "appname" must be declared.')
2015-02-24 11:05:51,879 pool _finalize_fairy 574 : Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.10-x86_64.egg/sqlalchemy/pool.py", line 567, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.10-x86_64.egg/sqlalchemy/pool.py", line 701, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.10-x86_64.egg/sqlalchemy/engine/default.py", line 406, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4471123968 and this is thread id 140735083598592
2015-02-24 11:05:51,880 pool _close_connection 255 : Exception closing connection <pysqlite2.dbapi2.Connection object at 0x10a30c3d0>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.10-x86_64.egg/sqlalchemy/pool.py", line 250, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SQLAlchemy-0.9.8-py2.7-macosx-10.10-x86_64.egg/sqlalchemy/engine/default.py", line 412, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4471123968 and this is thread id 140735083598592
