### ISSUE TITLE
fc17.x86_64 ImportError: cannot import name InstrumentationManager

### ISSUE THREAD

**Issue by zhoudd** [VitaliyRodnenko/geeknote#134]
```
#run 
 python geeknote.py login
```

```
#Error
Traceback (most recent call last):
  File "geeknote.py", line 30, in <module>
    import out
  File "/home/zhoudd/git/geeknote/out.py", line 8, in <module>
    import editor
  File "/home/zhoudd/git/geeknote/editor.py", line 13, in <module>
    from storage import Storage
  File "/home/zhoudd/git/geeknote/storage.py", line 8, in <module>
    from lib.sqlalchemy.orm import *
  File "/home/zhoudd/git/geeknote/lib/sqlalchemy/orm/__init__.py", line 22, in <module>
    from sqlalchemy.orm.interfaces import (
ImportError: cannot import name InstrumentationManager

```

**Comment by kzys** [comment]
@zhoudd Can you close this issue? Geeknote doesn't have the "lib" directory anymore. It was deleted at a3119bfab987f8b9cc1d4ce32ede85a47db03da9.
