### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by kirang89** [VitaliyRodnenko/geeknote#243]
I cloned the repo, created a virtualenv and ran the following commands:

```
python setup.py install
python setup.py test
```

but I ended up with this, while running the tests:

```
$ python setup.py test                 [3:23:16]
running test
running egg_info
writing requirements to geeknote.egg-info/requires.txt
writing geeknote.egg-info/PKG-INFO
writing top-level names to geeknote.egg-info/top_level.txt
writing dependency_links to geeknote.egg-info/dependency_links.txt
writing entry points to geeknote.egg-info/entry_points.txt
reading manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.MD'
warning: no previously-included files found matching '*.orig'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'geeknote.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    keywords='Evernote, console'
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/kiran/Workspace/geeknote/env/lib/python2.7/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/Users/kiran/Workspace/geeknote/env/lib/python2.7/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/Users/kiran/Workspace/geeknote/env/lib/python2.7/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/kiran/Workspace/geeknote/env/lib/python2.7/site-packages/setuptools/command/test.py", line 35, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/Users/kiran/Workspace/geeknote/tests/gnsyncTest.py", line 3, in <module>
    from geeknote.gnsync import remove_control_characters
  File "/Users/kiran/Workspace/geeknote/geeknote/gnsync.py", line 27, in <module>
    CONTROL_CHARS = ''.join(c for c in (unichr(i) for i in xrange(0x110000)) \
  File "/Users/kiran/Workspace/geeknote/geeknote/gnsync.py", line 27, in <genexpr>
    CONTROL_CHARS = ''.join(c for c in (unichr(i) for i in xrange(0x110000)) \
  File "/Users/kiran/Workspace/geeknote/geeknote/gnsync.py", line 27, in <genexpr>
    CONTROL_CHARS = ''.join(c for c in (unichr(i) for i in xrange(0x110000)) \
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
```

**Comment by kzys** [comment]
The issue would be fixed by 5756c6ccd589371b54eec93f3c9c7de27a45aacb.
