### ISSUE TITLE
ValueError: year is out of range

### ISSUE THREAD

**Issue by aegor** [VitaliyRodnenko/geeknote#259]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

$ env | grep LANG
LANG=ru_RU.UTF-8
GDM_LANG=ru
LANGUAGE=ru

$ geeknote find ubuntu
Search request: intitle:ubuntu          
Total found: 20
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 905, in main
    Notes().find(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 808, in find
    out.SearchResult(result.notes, request, showUrl=with_url)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 37, in wrapped
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 136, in SearchResult
    printList(listItems, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 34, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 241, in printList
    printDate(item.created).ljust(18, " ") if hasattr(item, 'created') else '',
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 277, in printDate
    return datetime.date.strftime(datetime.date.fromtimestamp(timestamp), "%d.%m.%Y")
ValueError: year is out of range

**Comment by jeffkowalski** [comment]
Do you know what the correct input date is for that note?  That might aid in debugging.
As well, "geeknote-0.2a" unfortunately refers to more than one revision of geeknote, since that release number has been recycled across many branches in github.  Perhaps you could try a more recent branch from here in github and respond with the result?
I ask because in my copy of geeknote for instance, I see a different implementation of printDate from the one you show above.

**Comment by aegor** [comment]
strange. 
in out.py, line 277
def printDate(timestamp):
    return datetime.date.strftime(datetime.date.fromtimestamp(timestamp/1000), "%d.%m.%Y")
i change "timestamp" to "timestamp/1000", as in this discussion: https://news.ycombinator.com/item?id=2766775
,and all worked ok.

**Comment by jeffkowalski** [comment]
@aegor: correct, that's the implementation I see in my branch:
https://github.com/jeffkowalski/geeknote/blob/master/geeknote/out.py#L280
```python
def printDate(timestamp):
    return datetime.datetime.fromtimestamp(timestamp/1000).strftime("%d.%m.%Y")
```

**Comment by kzys** [comment]
Since 4c526a528ae2f4f67c11a9145ba9a014e3b74232 changes printDate() as this thread recommends, we can close the issue.
