### ISSUE TITLE
Unicode chars not handled properly

### ISSUE THREAD

**Issue by fukuchi** [VitaliyRodnenko/geeknote#261]
Notes contains non-ASCII (Unicode) characters causes the following error when I tried to edit the note.

<pre>
$ geeknote edit --content WRITE --note Test
    : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 846, in main
    Notes().edit(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 609, in edit
    result = self._editWithEditorInThread(inputData, note)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 549, in _editWithEditorInThread
    editor = Editor(note.content)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 213, in __init__
    os.write(tempfileHandler, self.ENMLtoText(content))
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 103, in ENMLtoText
    content = html2text.html2text(str(soup))
  File "/usr/local/lib/python2.7/dist-packages/html2text-2014.12.29-py2.7.egg/html2text/__init__.py", line 750, in html2text
    return h.handle(html)
  File "/usr/local/lib/python2.7/dist-packages/html2text-2014.12.29-py2.7.egg/html2text/__init__.py", line 121, in handle
    return self.optwrap(self.close())
  File "/usr/local/lib/python2.7/dist-packages/html2text-2014.12.29-py2.7.egg/html2text/__init__.py", line 139, in close
    outtext = nochr.join(self.outtextlist)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
</pre>

**Comment by fukuchi** [comment]
The same error is observed with "geeknote show".

**Comment by Desiderata** [comment]
In geeknote/editor.py
line 103 change from "content = html2text.html2text(str(soup))"
to "content = html2text.html2text(str(soup).decode('utf-8'))"

It fixed the unicode problem for me.

**Comment by fukuchi** [comment]
Hi @Desiderata 

It works perfectly! Thank you for the patch.
