### ISSUE TITLE
Error creating/editing note

### ISSUE THREAD

**Issue by Munchotaur** [VitaliyRodnenko/geeknote#265]
Hi, I see the following error whenever I try to edit or create a note: 

geeknote create --title "geeknote test" --notebook "default" --content "some text here"
 >> : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 893, in main
    Notes().create(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 637, in create
    inputData = self._parseInput(title, content, tags, notebook, resource)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 705, in _parseInput
    "resources": resources if resources else [],
NameError: global name 'resources' is not defined

**Comment by jeffkowalski** [comment]
Like the same as https://github.com/VitaliyRodnenko/geeknote/issues/257

**Comment by kzys** [comment]
#257 was fixed already. Maybe we can close this issue also.
