### ISSUE TITLE
Cannot create/read/edit

### ISSUE THREAD

**Issue by KeriWarr** [VitaliyRodnenko/geeknote#272]
Recently downloaded and installed this software, setup script seemed to work correctly.

Here is what happens when I try to read a note:

```

$ geeknote create --title "test_note"
Note has been successfully created.     

$ geeknote show --note "test_note"
################## TITLE ##################
test_note
=================== META ==================
Created: 17.01.1970     
Updated: 17.01.1970     
----------------- CONTENT -----------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 902, in main
    Notes().show(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 697, in show
    out.showNote(note)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 37, in wrapped
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 180, in showNote
    printLine(Editor.ENMLtoText(note.content))
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 101, in ENMLtoText
    content = html2text.html2text(str(soup).decode('utf-8'), '', 0)
TypeError: html2text() takes at most 2 arguments (3 given)
```

I ran the test suite in case the output might be useful. Here is a link:

https://www.dropbox.com/s/zph0sqjnxg756mz/test.log?dl=0

**Comment by KeriWarr** [comment]
Also, here is a demonstration that I can connect to my Evernote profile, and I can see the notes, however I cannot read them either, and the metadata is wrong:

```
$ geeknote show "*"
Total found: 20                         
  1 : 17.01.1970        test_note
  2 : 17.01.1970        ###
  3 : 17.01.1970        ###
  4 : 17.01.1970        ###
  5 : 17.01.1970        ###
  6 : 17.01.1970        ###
  7 : 17.01.1970        ###
  8 : 17.01.1970        ###
  9 : 17.01.1970        ###
 10 : 17.01.1970        ###
 11 : 17.01.1970        ###
 12 : 17.01.1970        ###
 13 : 17.01.1970        ###
 14 : 17.01.1970        ###
 15 : 17.01.1970        ###
 16 : 17.01.1970        ###
 17 : 17.01.1970        ###
 18 : 17.01.1970        ###
 19 : 17.01.1970        ###
 20 : 17.01.1970        ###
  0 : -Cancel-
: 6
################## TITLE ##################
###
=================== META ==================
Created: 17.01.1970     
Updated: 17.01.1970     
longitude: -80.5436
source: mobile.android
latitude: 43.4723
----------------- CONTENT -----------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 902, in main
    Notes().show(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 697, in show
    out.showNote(note)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 37, in wrapped
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 180, in showNote
    printLine(Editor.ENMLtoText(note.content))
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 101, in ENMLtoText
    content = html2text.html2text(str(soup).decode('utf-8'), '', 0)
TypeError: html2text() takes at most 2 arguments (3 given)
```

**Comment by blutgens** [comment]
It's crashing trying to convert the HTML notes to a plain text format.

**Comment by martinRoss** [comment]
Trying Geeknote out for the first time now and I can confirm this error. I can login, view note lists, etc. but editing fails on the HTML --> plain text conversion. Running Ubuntu 14.04 with Python 2.7.6.

Removing the third argument in line 101 of "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py" fixes the error for me.

**Original**
```python
content = html2text.html2text(str(soup).decode('utf-8'), '', 0)
```

**Updated**
```python
content = html2text.html2text(str(soup).decode('utf-8'), '')
```

**Comment by robertoaloi** [comment]
Confirmed. Also @martinRoss 's fix works for me, too. Ubuntu 14.04.2 LTS.

**Comment by ErikBjare** [comment]
Anyone solved that nasty metadata bug?
