### ISSUE TITLE
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.

### ISSUE THREAD

**Issue by ShashankJ** [VitaliyRodnenko/geeknote#277]
Hi,
 when ever I am writing following line in my note and saving:
 <copy and paste SQL here>
it is throwing error
Error seen on console: Error while saving the note.
Error seen in ~/.geeknote/error.log:
2015-03-23 16:10:14,829 pool _close_connection 254 : Exception closing connection <sqlite3.Connection object at 0x10f40a3d0>
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-intel/egg/sqlalchemy/pool.py", line 251, in _close_connection
    self._dialect.do_close(connection)
  File "build/bdist.macosx-10.10-intel/egg/sqlalchemy/engine/default.py", line 418, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4573892608 and this is thread id 140735287530240

**Comment by creekhead** [comment]
This is a duplicate of issues/256
It appears that it is a combination of symbols < and >

If my note has <b> in it, it is oddly converted to *** and saved properly but if i have something like 
<anything> in the note it fails to save with the same error as above, anything like <fihf> seems to fail to save.. I see that < and > are converted to entities so this is just not converting correctly...

Noticed on WIN 10 64B

Small issue especially if you know how to avoid it...
Love GN, keep up the great work!
