### ISSUE TITLE
setup.py test fails at Amazon Linux

### ISSUE THREAD

**Issue by kissyjpf** [VitaliyRodnenko/geeknote#287]
setup.py test failes at Amazon Linux as below;

-bash-4.1$ python2 setup.py test
running test
running egg_info
writing requirements to geeknote.egg-info/requires.txt
writing geeknote.egg-info/PKG-INFO
writing top-level names to geeknote.egg-info/top_level.txt
writing dependency_links to geeknote.egg-info/dependency_links.txt
writing entry points to geeknote.egg-info/entry_points.txt
reading manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.MD'
warning: no previously-included files found matching '*.orig'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'geeknote.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    keywords='Evernote, console'
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.6/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.6/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.6/unittest.py", line 815, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.6/unittest.py", line 842, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.6/unittest.py", line 848, in createTests
    self.module)
  File "/usr/lib64/python2.6/unittest.py", line 612, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.6/unittest.py", line 575, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/ec2-user/geeknote-master/tests/__init__.py", line 9, in <module>
    from geeknote import tools
  File "/home/ec2-user/geeknote-master/geeknote/tools.py", line 3, in <module>
    import out
  File "/home/ec2-user/geeknote-master/geeknote/out.py", line 11, in <module>
    from editor import Editor
  File "/home/ec2-user/geeknote-master/geeknote/editor.py", line 40
    return {v:k for k, v in Editor.getHtmlEscapeTable().items()}
                  ^
SyntaxError: invalid syntax

**Comment by kzys** [comment]
Maybe you need Python 2.7. See #174 for the detail.

FYI, Python 2.6 is EOL.
https://www.python.org/dev/peps/pep-0361/
