### ISSUE TITLE
Wrong permission

### ISSUE THREAD

**Issue by mgrad** [VitaliyRodnenko/geeknote#302]
After sudo python setup.py install ~/.geeknote had wrong permissions.

**Comment by eremzeit** [comment]
Hah, I misunderstood how python package installation worked and I also added an extraneous `sudo` to `python setup.py install`.  Now those files have root ownership.  Simply deleting the local geeknote directories and reinstalling without the `sudo` doesn't work because the dependencies installed system-wide also were created with root ownership.

```
00:23 $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 11, in <module>
    from setuptools.extension import Extension
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 16, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2813, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 686, in subscribe
    callback(dist)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2813, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2343, in activate
    self.insert_on(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2430, in insert_on
    self.check_version_conflict()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2458, in check_version_conflict
    for modname in self._get_metadata('top_level.txt'):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2337, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1325, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1317, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1426, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.txt'
~/workspace/geeknote [master|✔] 
00:23 $ ls -la /Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.txt
-rw-r-----  1 root  wheel  9 Jul  8 00:19 /Library/Python/2.7/site-packages/httplib2-0.9.1-py2.7.egg/EGG-INFO/top_level.txt
~/workspace/geeknote [master|✔] 
00:26 $ 
```

**Comment by eremzeit** [comment]
This issue is related, but not exactly the same.  The author's problem is that items in the ~/.geeknote directory are owned by root.  My problem above is that system python packages are being installed as root and running geeknote fails when it tries to access those.

https://github.com/VitaliyRodnenko/geeknote/issues/211

**Comment by eremzeit** [comment]
Installing via pip using the command `sudo pip install` seems to have worked for me in that now I can run geeknote without `sudo`.  I'm not sure, however, if the issue here is inherent to HEAD or if just that pip does something differently.
