### ISSUE TITLE
Raw output not working

### ISSUE THREAD

**Issue by Cenness** [VitaliyRodnenko/geeknote#303]
```
# geeknote show notename -w
Traceback (most recent call last):      
  File "/usr/lib/python2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 902, in main
    Notes().show(**ARGS)
  File "/usr/lib/python2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 695, in show
    out.showNoteRaw(note)
  File "/usr/lib/python2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 37, in wrapped
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/out.py", line 184, in showNoteRaw
    printLine(Editor.ENMLtoText(note.content, 'pre'))
TypeError: ENMLtoText() takes exactly 1 argument (2 given)
```
Original pull request with feature: https://github.com/VitaliyRodnenko/geeknote/pull/254

**Comment by MatrixManAtYrService** [comment]
Ran across this as well.  Took a crack at it, but my python-foo is not strong.   Here's what I learned.

Looks like [this](https://github.com/VitaliyRodnenko/geeknote/commit/ec8dd5b97a4efd66e96cac599138b3c901f0eaed) commit dropped the `format` parameter from Editor.textToENML, but `out.py` still uses that parameter to pass in `'pre'`
