### ISSUE TITLE
unable to geeknote login

### ISSUE THREAD

**Issue by hatelove85911** [VitaliyRodnenko/geeknote#304]
After installation of geeknote, when I try to `geeknote login`, I got the following errors:
PS: I don't know if it's caused by I'm sitting behind a corporate proxy, if yes, is there a work around?

```
>>  : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 883, in main
    User().login(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 397, in login
    if self.getEvernote().auth():
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 151, in auth
    self.authToken = GNA.getToken()
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/oauth.py", line 133, in getToken
    self.getTmpOAuthToken()
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/oauth.py", line 151, in getTmpOAuthToken
    oauth_callback="https://" + self.url['base']
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/oauth.py", line 104, in loadPage
    conn.request(method, uri, params, headers)
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
```

**Comment by RuBiCK** [comment]
I have the same problem and I'm using ENV proxy.
do geeknote read proxy from ENV vars? 
can I specify by command line proxy settings?
