### ISSUE TITLE
Error when editing a note

### ISSUE THREAD

**Issue by milin** [VitaliyRodnenko/geeknote#321]
>> : Connect to Evernote.../Library/Python/2.7/site-packages/beautifulsoup4-4.4.0-py2.7.egg/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser")
. This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

    : Connect to Evernote...Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 174, in textToENML
    Editor.checklistInSoupToENML(soup)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/editor.py", line 148, in checklistInSoupToENML
    pre = str_re.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Error while parsing text to html. Content must be an UTF-8 encode.

**Comment by DonHansDampf** [comment]
Same problem on Mac. Doesn't matter if Yosemite oder El Captian. But it seems like, nobody is working at geeknote anymore...

**Comment by jaguarondi** [comment]
This fork seems quite active: https://github.com/VitaliyRodnenko/geeknote

**Comment by patrickmcelwee** [comment]
This is an issue with some special handling for list checkboxes (`[ ]`). I was able to workaround it. The problem came up when my lines started with `[ ]`. If, instead, I started them like this: `* [ ]`, this error stopped occurring, and I got the right results in Evernote

**Comment by patrickmcelwee** [comment]
same as #310
