### ISSUE TITLE
 BeautifulSoup([your markup], "lxml")

### ISSUE THREAD

**Issue by mattcurrycom** [VitaliyRodnenko/geeknote#366]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 174, in textToENML
    Editor.checklistInSoupToENML(soup)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 148, in checklistInSoupToENML
    pre = str_re.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 174, in textToENML
    Editor.checklistInSoupToENML(soup)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 148, in checklistInSoupToENML
    pre = str_re.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 174, in textToENML
    Editor.checklistInSoupToENML(soup)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/editor.py", line 148, in checklistInSoupToENML
    pre = str_re.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
/usr/lib/python2.7/dist-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))

**Comment by jeffkowalski** [comment]
duplicate of #352, #317, #321, #364, #354, #305, #307, #331, #334
