### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by LondonAppDev** [VitaliyRodnenko/geeknote#372]
I just downloaded geeknote and installed from source.

It looks like the login oauth flow is broken. 

I enter my login email address, and then it asks me for the two-factor auth code (even when that's not enabled), and then the log just outputs this:

`2016-11-03 15:16:33,385 oauth allowAccess 251 : Unexpected response status on allowing access 302 != 403`

Will try debug myself a bit later.

**Comment by blackkenny** [comment]
I have exactly the same issue. Any updates on this?

**Comment by jeffkowalski** [comment]
Does it also fail on  in this branch: 3a5d2801313faacdf0ceb63d29190a910de46618 ?

**Comment by jackhamm** [comment]
I am also experiencing this problem attempting to login.  In my setup I also have 2FA enabled.

**Comment by gentoolovers** [comment]
I have the same issue.On gentoo.

**Comment by mojoman** [comment]
Same issue here on OS X, clone from master, no two-factor auth.

**Comment by sunisdown** [comment]
same issue. On macOS

the response data is `csrf_failure`

**Comment by xkpd3** [comment]
+1 (Debian testing and FreeBSD 11-RELEASE)

**Comment by Jfeng3** [comment]
+1

**Comment by arpan-chavda** [comment]
Same issue.

**Comment by edgargalvan** [comment]
Same on Ubuntu 16.04 LTS & OS X El Capitan

**Comment by pipakin** [comment]
https://github.com/VitaliyRodnenko/geeknote/pull/374

This should fix it. It was a csrf token failure. Evernote was outputting two csrf token hidden fields that needed to be sent along with the request.

**Comment by xkpd3** [comment]
@pipakin: I can confirm that your fix works. It is still asking for the second factor, but just hitting enter successfully logged me in. Subsequent commands are working fine.

**Comment by pipakin** [comment]
Yup, the two factor is a different thing. It should work either way.  Internally they changed the process to always return a 302 (redirect) to send you to an analytics page. before it seems that only happened with tfa.  Now it always tried the tfa but if you leave it blank it will work if you don't have tfa enabled.

**Comment by eanogueyra** [comment]
I just installed Geeknote and have the same two-factor login  problem on Kubuntu 16.04. I have applied the above mentioned fix on the geeknote/oauth.py  file  without success.

**Comment by liveconvinced** [comment]
installed today on OS X 10.11.6
Despite installation going smoothly, all that happens is prompts for authentication...
Every time I authenticate, nothing happens. I'm returned back to the command prompt.

Sure hope it can be resolved soon. Don't know what I could do to troubleshoot further.

**Comment by mdhighfi** [comment]
I also installed Geeknote on OS X 10.11.6 and I am simply returned to the prompt after auth.

same as @liveconvinced above.

**Comment by xkpd3** [comment]
People: Go to Graphs -> Network on this page. Then you will see that this repository is terribly outdated.

The issue has been fixed for quiet some time here: https://github.com/jeffkowalski/geeknote

**Comment by mdhighfi** [comment]
It didn't work and I gave up (don't remember the details).  Then today I tried again.  I tried:
```
brew install --HEAD https://raw.githubusercontent.com/jeffkowalski/geeknote/master/geeknote.rb
```
[_insert brew doing many things here_]
```
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/geeknote/HEAD-2b5f8fc/libexec/vendor
--single-version-externally-managed
--record=installed.txt

error in docker-py setup command: Invalid environment marker: python_version < "3.5"

Do not report this issue to Homebrew/brew or Homebrew/core!
```
Looked up the error and didn't find much.  I then remembered that when this failed a few weeks ago I tried installing a later version of Python, but got more errors going that route.  

Next I tried replacing the repo listed in the [geeknote installation instructions](https://www.geeknote.me/install/) with `https://github.com/jeffkowalski/geeknote`:

```
> git clone git://github.com/jeffkowalski/geeknote
...
> cd geeknote/
> sudo python setup.py install
...
> geeknote login
Traceback (most recent call last):
  File "/usr/local/bin/geeknote", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: lxml
```

I did a quick search and found [this installation issue](https://github.com/neilagabriel/vim-geeknote/issues/12) which is not the same as mine.  Going to take a break from messing with this again and try some other tools for now.  But I'll probably revisit geeknote when I'm bold enough to try again.

**Comment by semtle** [comment]
I have the same issue with mdhighfi...

**Comment by Elinpf** [comment]
Tanks very much !

**Comment by d7bh** [comment]
Hi,
If you have still issues you need to install this version: https://github.com/jeffkowalski/geeknote and compile libs with python 2.7:
https://pypi.python.org/pypi/proxyenv
https://pypi.python.org/pypi/lxml/2.3
then install geeknote with python 2.7.

**Comment by jameswq** [comment]
I have the same issue +1
