### ISSUE TITLE
Geeknote throws error while running any command on console

### ISSUE THREAD

**Issue by designgeef** [VitaliyRodnenko/geeknote#373]
Here's the output that I am getting:
```
>>  : Connect to Evernote...Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 889, in main
    User().settings(**ARGS)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/geeknote-0.2a-py2.7.egg/geeknote/geeknote.py", line 442, in settings
    user = user_settings[1]['info']
IndexError: list index out of range
```

Steps to reproduce:
1. On mac 10.11.6 (El Capitan), follow the instructions to install (from source, in sudo mode) as written here: http://www.geeknote.me/documentation/
2. Login to the evernote account (no errors were seen here)
3. Run `geeknote settings`

Also:
1. tests fail (`sudo python setup.py test`)
2. Spacemacs does not detect logged in user when invoking `geeknote-user`

Let me know if the issue ticket is not clear enough. Thanks!

**Comment by jwbowers** [comment]
+1 

```
Last login: Wed Nov 16 14:07:52 on ttys000
$ geeknote settings
>>  : Connecting to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote/geeknote.py", line 1214, in main
    User().settings(**ARGS)
  File "/usr/local/lib/python2.7/site-packages/geeknote/geeknote.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote/geeknote.py", line 612, in settings
    user = user_settings[1]['info']
IndexError: list index out of range
```

**Comment by king-c** [comment]
Same issue here

**Comment by alex1a** [comment]
+1, on last raspbian with pixel, in raspberrypi 2
"Linux raspberrypi 4.4.34-v7+ #930 SMP Wed Nov 23 15:20:41 GMT 2016 armv7l GNU/Linux"

**Comment by knocatomi** [comment]
same issue here. Just went through the uninstall/reinstall process and same issue.

**Comment by jorgt** [comment]
Here too, OSX Sierra

**Comment by songpeng** [comment]
Here too, OSX Sierra.

**Comment by moisesnalves** [comment]
Same here. Ubuntu 16.04 server

>>  : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 889, in main
    User().settings(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 442, in settings
    user = user_settings[1]['info']
IndexError: list index out of range

**Comment by zephirefaith** [comment]
+1 on Ubuntu 14.04

**Comment by Kamoris** [comment]
+1 on Linux Mint 18.1 Cinnamon

**Comment by RioZRon** [comment]
➜ GG T.T
 ```
geeknote git:(master) geeknote settings
>>  : Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 889, in main
    User().settings(**ARGS)
  File "/usr/local/lib/python2.7/site-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 442, in settings
    user = user_settings[1]['info']
IndexError: list index out of range
```

**Comment by RioZRon** [comment]
!   it works
git clone https://github.com/pipakin/geeknote.git

**Comment by ranjitc** [comment]
@RioZRon that repo didn't work for me on osx, what platform are you on?
