### ISSUE TITLE
Unable to login behind a corporate proxy

### ISSUE THREAD

**Issue by fabuloso** [VitaliyRodnenko/geeknote#379]
On my debian, when I try to login it throws this exception:

` Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 883, in main
    User().login(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 397, in login
    if self.getEvernote().auth():
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/geeknote.py", line 151, in auth
    self.authToken = GNA.getToken()
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/oauth.py", line 133, in getToken
    self.getTmpOAuthToken()
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/oauth.py", line 151, in getTmpOAuthToken
    oauth_callback="https://" + self.url['base']
  File "/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg/geeknote/oauth.py", line 104, in loadPage
    conn.request(method, uri, params, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
`

**Comment by nocivus** [comment]
Managed to go as far as receiving the credentials and two factor code by replacing some code in: /usr/local/lib/python2.7/dist-packages/geeknote-0.2a-py2.7.egg/geeknote/oauth.py

Line 104 (or close):

       #conn = httplib.HTTPSConnection(url)                                                                                                                                     
        conn = httplib.HTTPSConnection("localhost", 3128)
        conn.set_tunnel(url, 443)

But now i have another problem which is: Geeknote does not store the credentials, nor does it execute anything i ask after i enter all credentials.
