### ISSUE TITLE
Geeknote 2.0.10 requires urllib3<1.22 but 1.22 is installed

### ISSUE THREAD

**Issue by SilkAndSlug** [VitaliyRodnenko/geeknote#386]
I guess this is actually a PIP bug, but I can't see where to add this...

`geeknote create` fails with an error[1] ending:

    pkg_resources.DistributionNotFound: The 'urllib3<1.22,>=1.21.1' distribution was not found and is required by requests

`pip list | grep urllib3` echoes "1.22". `pip check geeknote` echoes "No broken requirements found."

FYI, `pip list | grep geeknote` echoes "2.0.10"

**Comment by SilkAndSlug** [comment]
[1]

Command (run by cron):

    geeknote create --title "test" --tags "@Anywhere,#ASAP" --notebook ".SMUGs"

Error:

```
Traceback (most recent call last):
  File "/usr/local/bin/geeknote", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 659, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 672, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 857, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urllib3<1.22,>=1.21.1' distribution was not found and is required by requests
```

It also raises a `Unexpected argument "--tags" for command "create"` error, but fixing that hides the above error.
