### ISSUE TITLE
Install fails on macOs High-Sierra, Anaconda Python

### ISSUE THREAD

**Issue by mgiugliano** [VitaliyRodnenko/geeknote#392]
This is the output of > sudo python setup.py install

```

/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '0.2a' to '0.2a0'
  normalized_version,
running install
running bdist_egg
running egg_info
creating geeknote.egg-info
writing geeknote.egg-info/PKG-INFO
writing dependency_links to geeknote.egg-info/dependency_links.txt
writing entry points to geeknote.egg-info/entry_points.txt
writing requirements to geeknote.egg-info/requires.txt
writing top-level names to geeknote.egg-info/top_level.txt
writing manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.orig'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'geeknote.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/geeknote
copying geeknote/config.py -> build/lib/geeknote
copying geeknote/gnsync.py -> build/lib/geeknote
copying geeknote/log.py -> build/lib/geeknote
copying geeknote/out.py -> build/lib/geeknote
copying geeknote/tools.py -> build/lib/geeknote
copying geeknote/__init__.py -> build/lib/geeknote
copying geeknote/storage.py -> build/lib/geeknote
copying geeknote/gclient.py -> build/lib/geeknote
copying geeknote/editor.py -> build/lib/geeknote
copying geeknote/geeknote.py -> build/lib/geeknote
copying geeknote/argparser.py -> build/lib/geeknote
copying geeknote/oauth.py -> build/lib/geeknote
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/config.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/gnsync.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/log.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/out.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/tools.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/storage.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/gclient.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/editor.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/geeknote.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/argparser.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
copying build/lib/geeknote/oauth.py -> build/bdist.macosx-10.7-x86_64/egg/geeknote
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/config.py to config.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/config.py", line 51
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/gnsync.py to gnsync.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/gnsync.py", line 44
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/log.py to log.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/out.py to out.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/out.py", line 109
    except (KeyboardInterrupt, SystemExit), e:
                                          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/tools.py to tools.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/storage.py to storage.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/storage.py", line 115
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/gclient.py to gclient.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/editor.py to editor.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/geeknote.py to geeknote.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/geeknote.py", line 69
    except Exception, e:
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/argparser.py to argparser.cpython-36.pyc
  File "build/bdist.macosx-10.7-x86_64/egg/geeknote/argparser.py", line 393
    print ""  # "Please_input_%s" % INP_ARG.replace('-', '')
           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.7-x86_64/egg/geeknote/oauth.py to oauth.cpython-36.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/entry_points.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/not-zip-safe -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying geeknote.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
creating dist
creating 'dist/geeknote-0.2a0-py3.6.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing geeknote-0.2a0-py3.6.egg
creating /Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg
Extracting geeknote-0.2a0-py3.6.egg to /Users/michi/anaconda/lib/python3.6/site-packages
  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/argparser.py", line 393
    print ""  # "Please_input_%s" % INP_ARG.replace('-', '')
           ^
SyntaxError: invalid syntax

  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/config.py", line 51
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/geeknote.py", line 69
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/gnsync.py", line 44
    except Exception, e:
                    ^
SyntaxError: invalid syntax

  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/out.py", line 109
    except (KeyboardInterrupt, SystemExit), e:
                                          ^
SyntaxError: invalid syntax

  File "/Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg/geeknote/storage.py", line 115
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Adding geeknote 0.2a0 to easy-install.pth file
Installing geeknote script to /Users/michi/anaconda/bin
Installing gnsync script to /Users/michi/anaconda/bin

Installed /Users/michi/anaconda/lib/python3.6/site-packages/geeknote-0.2a0-py3.6.egg
Processing dependencies for geeknote==0.2a0
Searching for thrift
Reading https://pypi.python.org/simple/thrift/
Downloading https://files.pythonhosted.org/packages/c6/b4/510617906f8e0c5660e7d96fbc5585113f83ad547a3989b80297ac72a74c/thrift-0.11.0.tar.gz#sha256=7d59ac4fdcb2c58037ebd4a9da5f9a49e3e034bf75b3f26d9fe48ba3d8806e6b
Best match: thrift 0.11.0
Processing thrift-0.11.0.tar.gz
Writing /tmp/easy_install-a7fo8c3t/thrift-0.11.0/setup.cfg
Running thrift-0.11.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a7fo8c3t/thrift-0.11.0/egg-dist-tmp-c2mhzd0y
In file included from src/ext/module.cpp:22:
In file included from src/ext/binary.h:25:
src/ext/endian.h:83:9: warning: 'ntohll' macro redefined [-Wmacro-redefined]
#define ntohll(n) ((((unsigned long long)ntohl(n)) << 32) + ntohl(n >> 32))
        ^
/usr/include/sys/_endian.h:140:9: note: previous definition is here
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
        ^
In file included from src/ext/module.cpp:22:
In file included from src/ext/binary.h:25:
src/ext/endian.h:84:9: warning: 'htonll' macro redefined [-Wmacro-redefined]
#define htonll(n) ((((unsigned long long)htonl(n)) << 32) + htonl(n >> 32))
        ^
/usr/include/sys/_endian.h:141:9: note: previous definition is here
#define htonll(x)       __DARWIN_OSSwapInt64(x)
        ^
2 warnings generated.
In file included from src/ext/binary.cpp:20:
In file included from src/ext/binary.h:25:
src/ext/endian.h:83:9: warning: 'ntohll' macro redefined [-Wmacro-redefined]
#define ntohll(n) ((((unsigned long long)ntohl(n)) << 32) + ntohl(n >> 32))
        ^
/usr/include/sys/_endian.h:140:9: note: previous definition is here
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
        ^
In file included from src/ext/binary.cpp:20:
In file included from src/ext/binary.h:25:
src/ext/endian.h:84:9: warning: 'htonll' macro redefined [-Wmacro-redefined]
#define htonll(n) ((((unsigned long long)htonl(n)) << 32) + htonl(n >> 32))
        ^
/usr/include/sys/_endian.h:141:9: note: previous definition is here
#define htonll(x)       __DARWIN_OSSwapInt64(x)
        ^
2 warnings generated.
In file included from src/ext/compact.cpp:20:
In file included from src/ext/compact.h:25:
src/ext/endian.h:83:9: warning: 'ntohll' macro redefined [-Wmacro-redefined]
#define ntohll(n) ((((unsigned long long)ntohl(n)) << 32) + ntohl(n >> 32))
        ^
/usr/include/sys/_endian.h:140:9: note: previous definition is here
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
        ^
In file included from src/ext/compact.cpp:20:
In file included from src/ext/compact.h:25:
src/ext/endian.h:84:9: warning: 'htonll' macro redefined [-Wmacro-redefined]
#define htonll(n) ((((unsigned long long)htonl(n)) << 32) + htonl(n >> 32))
        ^
/usr/include/sys/_endian.h:141:9: note: previous definition is here
#define htonll(x)       __DARWIN_OSSwapInt64(x)
        ^
2 warnings generated.
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
creating /Users/michi/anaconda/lib/python3.6/site-packages/thrift-0.11.0-py3.6-macosx-10.7-x86_64.egg
Extracting thrift-0.11.0-py3.6-macosx-10.7-x86_64.egg to /Users/michi/anaconda/lib/python3.6/site-packages
Adding thrift 0.11.0 to easy-install.pth file

Installed /Users/michi/anaconda/lib/python3.6/site-packages/thrift-0.11.0-py3.6-macosx-10.7-x86_64.egg
Searching for markdown2
Reading https://pypi.python.org/simple/markdown2/
Downloading https://files.pythonhosted.org/packages/64/75/03ad43fdc360438357ecc0c8e98b739ec204276fe4c64a684df6883dffeb/markdown2-2.3.5.zip#sha256=8bb9a24eb2aa02f1427aabe46483f0f0215ab18c8a345315ae8e2ee3c3a09c03
Best match: markdown2 2.3.5
Processing markdown2-2.3.5.zip
Writing /tmp/easy_install-l7lbjv0b/markdown2-2.3.5/setup.cfg
Running markdown2-2.3.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l7lbjv0b/markdown2-2.3.5/egg-dist-tmp-dgtfdy21
zip_safe flag not set; analyzing archive contents...
__pycache__.markdown2.cpython-36: module references __file__
creating /Users/michi/anaconda/lib/python3.6/site-packages/markdown2-2.3.5-py3.6.egg
Extracting markdown2-2.3.5-py3.6.egg to /Users/michi/anaconda/lib/python3.6/site-packages
Adding markdown2 2.3.5 to easy-install.pth file
Installing markdown2 script to /Users/michi/anaconda/bin

Installed /Users/michi/anaconda/lib/python3.6/site-packages/markdown2-2.3.5-py3.6.egg
Searching for html2text
Reading https://pypi.python.org/simple/html2text/
Downloading https://files.pythonhosted.org/packages/16/20/de2b458ef434713053dd83209a03a5431ebe0527c8e14d9ae7838ff67d8a/html2text-2018.1.9-py3-none-any.whl#sha256=490db40fe5b2cd79c461cf56be4d39eb8ca68191ae41ba3ba79f6cb05b7dd662
Best match: html2text 2018.1.9
Processing html2text-2018.1.9-py3-none-any.whl
Installing html2text-2018.1.9-py3-none-any.whl to /Users/michi/anaconda/lib/python3.6/site-packages
Adding html2text 2018.1.9 to easy-install.pth file
Installing html2text script to /Users/michi/anaconda/bin

Installed /Users/michi/anaconda/lib/python3.6/site-packages/html2text-2018.1.9-py3.6.egg
Searching for evernote>=1.17
Reading https://pypi.python.org/simple/evernote/
Downloading https://files.pythonhosted.org/packages/f9/6b/877f8edef8ef040d32eb38f3bf6322ba334de9d10614d8db9d869c162fc1/evernote-1.25.3.tar.gz#sha256=796847e0b7517e729041c5187fa1665c3f6fc0491cb4d71fb95a62c4f22e64eb
Best match: evernote 1.25.3
Processing evernote-1.25.3.tar.gz
Writing /tmp/easy_install-nxqzm16b/evernote-1.25.3/setup.cfg
Running evernote-1.25.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nxqzm16b/evernote-1.25.3/egg-dist-tmp-4zh32hw8
Traceback (most recent call last):
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-nxqzm16b/evernote-1.25.3/setup.py", line 6
    exec x
         ^
SyntaxError: Missing parentheses in call to 'exec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./setup.py", line 108, in <module>
    keywords='Evernote, console'
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/Users/michi/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/michi/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/michi/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/michi/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/Users/michi/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 882, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1150, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1136, in run_setup
    run_setup(setup_script, args)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/Users/michi/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/michi/anaconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/Users/michi/anaconda/lib/python3.6/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-nxqzm16b/evernote-1.25.3/setup.py", line 6
    exec x
         ^
SyntaxError: Missing parentheses in call to 'exec'
```

**Comment by tiev** [comment]
I have successfully installed with these steps:

```
$ python setup.py build
$ pip2 install --upgrade .
```

But I still have an error when running login.

**Comment by FrenchFlakito** [comment]
Hi,

For me ensuring that the `python setup.py install` command ran with Python **2** did the trick. For me the answer was simply calling
`python2 setup.py install`
instead of 
`python setup.py install`

**Comment by shwangdev** [comment]
seems that your were installing wiht Python3

**Comment by mgiugliano** [comment]
I understand that Python2 is required to install and have Geeknote up and running. I pass on it for now. Thank you all for your feedback and help.

**Comment by mgiugliano** [comment]
I understand that Python2 is required to install and have Geeknote up and running. I pass on it for now. Thank you all for your feedback and help.
