### ISSUE TITLE
Can't install on Ubuntu 20.04

### ISSUE THREAD

**Issue by silviubogan** [VitaliyRodnenko/geeknote#395]
I expected it to work but...

This is the install command (the second time I run it) and its output:

```
silviu@silviu-Inspiron-3537 ~/D/p/geeknote (master)> sudo python setup.py install
/usr/lib/python2.7/dist-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.2a' to '0.2a0'
  normalized_version,
running install
running bdist_egg
running egg_info
writing requirements to geeknote.egg-info/requires.txt
writing geeknote.egg-info/PKG-INFO
writing top-level names to geeknote.egg-info/top_level.txt
writing dependency_links to geeknote.egg-info/dependency_links.txt
writing entry points to geeknote.egg-info/entry_points.txt
reading manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.MD'
warning: no previously-included files found matching '*.orig'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'geeknote.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/out.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/storage.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/gnsync.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/log.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/gclient.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/oauth.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/config.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/geeknote.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/__init__.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/argparser.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/editor.py -> build/bdist.linux-x86_64/egg/geeknote
copying build/lib.linux-x86_64-2.7/geeknote/tools.py -> build/bdist.linux-x86_64/egg/geeknote
byte-compiling build/bdist.linux-x86_64/egg/geeknote/out.py to out.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/storage.py to storage.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/gnsync.py to gnsync.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/log.py to log.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/gclient.py to gclient.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/oauth.py to oauth.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/geeknote.py to geeknote.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/argparser.py to argparser.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/editor.py to editor.pyc
byte-compiling build/bdist.linux-x86_64/egg/geeknote/tools.py to tools.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying geeknote.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/geeknote-0.2a0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing geeknote-0.2a0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg
Extracting geeknote-0.2a0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
geeknote 0.2a0 is already the active version in easy-install.pth
Installing geeknote script to /usr/local/bin
Installing gnsync script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/geeknote-0.2a0-py2.7.egg
Processing dependencies for geeknote==0.2a0
Searching for html2text
Reading https://pypi.org/simple/html2text/
Downloading https://files.pythonhosted.org/packages/6c/f9/033a17d8ea8181aee41f20c74c3b20f1ccbefbbc3f7cd24e3692de99fb25/html2text-2020.1.16.tar.gz#sha256=e296318e16b059ddb97f7a8a1d6a5c1d7af4544049a01e261731d2d5cc277bbb
Best match: html2text 2020.1.16
Processing html2text-2020.1.16.tar.gz
Writing /tmp/easy_install-hisBmw/html2text-2020.1.16/setup.cfg
Running html2text-2020.1.16/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hisBmw/html2text-2020.1.16/egg-dist-tmp-6wy18m
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    keywords='Evernote, console'
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 449, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 691, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 738, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 783, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 710, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 736, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 921, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1189, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1175, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-hisBmw/html2text-2020.1.16/setup.py", line 3, in <module>
    
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 121, in parse_configuration
    meta.parse()
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 515, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 350, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'
```

The first time I got an error with red in the console (something with `fatal`), something not in the above command output. I tried deleting all the files and remaking a clone of geeknote but that error still does not appear. What would be the command for uninstall, so that I can show the initial output of the setup command?

Anyway, the next command I ran is:

```
silviu@silviu-Inspiron-3537 ~/D/p/geeknote (master) [1]> geeknote
Traceback (most recent call last):
  File "/usr/local/bin/geeknote", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'html2text' distribution was not found and is required by geeknote
```

The following commands worked well before all the commands above:

```
sudo apt-get update
sudo apt-get -y install python-setuptools
```

Also:

```
silviu@silviu-Inspiron-3537 ~/D/p/geeknote (master) [1]> python --version
Python 2.7.18rc1
```

I use the fish shell.

Thank you.

**Comment by ubuntupunk** [comment]
I can confirm this to be the case as well, bash.

**Comment by af0b9b** [comment]
same thing I also see on ubuntu 18.04: AttributeError: 'module' object has no attribute '__version__'

**Comment by jsilve24** [comment]
I am also having this problem on Ubuntu 20.04

**Comment by emacsway** [comment]
I also can confirm this
